<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pathologie;
use App\Models\User;

class FinalPathologieSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first();

        $pathologies = [
            // MALADIES RESPIRATOIRES
            ['nom' => 'Bronchopneumopathie chronique obstructive', 'categorie' => 'Pneumologie', 'description' => 'Maladie pulmonaire progressive causant une obstruction permanente des voies aériennes.', 'symptomes' => 'Toux chronique, essoufflement progressif, expectoration, sifflements, fatigue', 'cause' => 'Tabagisme chronique (90% des cas), pollution atmosphérique, expositions professionnelles aux poussières et fumées', 'prevention' => 'Arrêt du tabac, éviter la pollution, port de masque en milieu professionnel exposé', 'traitement_naturel' => 'Eucalyptus en inhalation, gingembre anti-inflammatoire, respiration diaphragmatique, yoga', 'gravite' => 'grave', 'contagieux' => 'non'],
            ['nom' => 'Pneumothorax', 'categorie' => 'Pneumologie', 'description' => 'Présence anormale d\'air entre le poumon et la paroi thoracique causant un collapsus pulmonaire.', 'symptomes' => 'Douleur thoracique soudaine, essoufflement brutal, tachycardie, diminution du murmure vésiculaire', 'cause' => 'Rupture spontanée de bulles d\'emphysème, traumatisme thoracique, complication de maladies pulmonaires', 'prevention' => 'Arrêt du tabac, éviter les activités à risque chez les sujets prédisposés', 'traitement_naturel' => 'Urgence médicale — repos strict, respiration contrôlée, plantes anti-inflammatoires en complément', 'gravite' => 'grave', 'contagieux' => 'non'],

            // MALADIES CARDIOVASCULAIRES
            ['nom' => 'Artérite des membres inférieurs', 'categorie' => 'Cardiologie', 'description' => 'Obstruction progressive des artères des jambes causant des douleurs à la marche.', 'symptomes' => 'Claudication intermittente, douleurs au mollet, pied froid, plaies qui ne cicatrisent pas', 'cause' => 'Athérosclérose, tabagisme, diabète, hypertension, hypercholestérolémie', 'prevention' => 'Arrêt du tabac, activité physique, alimentation saine, contrôle du diabète et tension', 'traitement_naturel' => 'Ail, ginkgo biloba, oméga-3, marche progressive, massage doux des membres', 'gravite' => 'grave', 'contagieux' => 'non'],
            ['nom' => 'Anévrisme aortique', 'categorie' => 'Cardiologie', 'description' => 'Dilatation anormale de l\'aorte pouvant se rompre et causer une hémorragie interne mortelle.', 'symptomes' => 'Souvent silencieux, douleur abdominale ou dorsale soudaine, masse pulsatile abdominale', 'cause' => 'Athérosclérose, hypertension artérielle, tabagisme, facteurs génétiques, syndrome de Marfan', 'prevention' => 'Contrôle de la tension artérielle, arrêt du tabac, dépistage chez les personnes à risque', 'traitement_naturel' => 'Ail, curcuma, oméga-3 pour protéger les vaisseaux, yoga pour réduire la tension', 'gravite' => 'grave', 'contagieux' => 'non'],

            // MALADIES DIGESTIVES
            ['nom' => 'Occlusion intestinale', 'categorie' => 'Gastroentérologie', 'description' => 'Obstruction du tube digestif empêchant le transit intestinal normal constituant une urgence.', 'symptomes' => 'Douleurs abdominales intenses, vomissements, arrêt des matières et gaz, ballonnement', 'cause' => 'Adhérences post-opératoires, hernie étranglée, tumeur, volvulus, corps étranger', 'prevention' => 'Traitement des hernies, suivi après chirurgie abdominale, alimentation équilibrée', 'traitement_naturel' => 'Urgence chirurgicale — en prévention : graines de lin, psyllium, hydratation abondante', 'gravite' => 'grave', 'contagieux' => 'non'],
            ['nom' => 'Appendicite', 'categorie' => 'Gastroentérologie', 'description' => 'Inflammation aiguë de l\'appendice nécessitant une intervention chirurgicale urgente.', 'symptomes' => 'Douleur fosse iliaque droite, fièvre, nausées, vomissements, défense abdominale', 'cause' => 'Obstruction de l\'appendice par des fèces durcies, corps étrangers ou infections bactériennes', 'prevention' => 'Alimentation riche en fibres, hydratation suffisante, hygiène alimentaire correcte', 'traitement_naturel' => 'Urgence chirurgicale — en prévention : graines de lin, aloe vera, probiotiques', 'gravite' => 'grave', 'contagieux' => 'non'],

            // MALADIES NEUROLOGIQUES
            ['nom' => 'Traumatisme crânien', 'categorie' => 'Neurologie', 'description' => 'Lésion cérébrale causée par un choc violent à la tête pouvant avoir des séquelles durables.', 'symptomes' => 'Perte de conscience, maux de tête, confusion, vomissements, troubles de la mémoire', 'cause' => 'Accidents de la route, chutes, sports de contact, violences physiques', 'prevention' => 'Port du casque, ceinture de sécurité, prévention des chutes chez les personnes âgées', 'traitement_naturel' => 'Urgence médicale — en rééducation : oméga-3, curcuma neuroprotecteur, méditation, sommeil suffisant', 'gravite' => 'grave', 'contagieux' => 'non'],
            ['nom' => 'Neuropathie périphérique', 'categorie' => 'Neurologie', 'description' => 'Atteinte des nerfs périphériques causant douleurs et engourdissements dans les extrémités.', 'symptomes' => 'Engourdissements, picotements, douleurs brûlantes, faiblesse musculaire, troubles de l\'équilibre', 'cause' => 'Diabète, alcoolisme, carence en vitamines B, maladies auto-immunes, médicaments toxiques', 'prevention' => 'Contrôle du diabète, arrêt de l\'alcool, supplémentation en vitamines B, alimentation équilibrée', 'traitement_naturel' => 'Vitamine B12, acide alpha-lipoïque, huile d\'onagre, capsaïcine topique, acupuncture', 'gravite' => 'modérée', 'contagieux' => 'non'],

            // MALADIES INFECTIEUSES NOUVELLES
            ['nom' => 'Fièvre de Crimée-Congo', 'categorie' => 'Virologie', 'description' => 'Fièvre hémorragique virale transmise par les tiques répandue en Afrique, Asie et Europe.', 'symptomes' => 'Fièvre soudaine, douleurs musculaires, maux de tête, hémorragies, nausées, vomissements', 'cause' => 'Virus Nairovirus transmis par morsure de tiques Hyalomma ou contact avec sang animal infecté', 'prevention' => 'Protection contre les tiques, éviter contact avec animaux malades, équipements de protection', 'traitement_naturel' => 'Hospitalisation urgente — en soutien : plantes immunostimulantes, hydratation, repos strict', 'gravite' => 'grave', 'contagieux' => 'oui'],
            ['nom' => 'Hépatite D', 'categorie' => 'Virologie', 'description' => 'Infection virale du foie ne survenant qu\'en présence du virus de l\'hépatite B.', 'symptomes' => 'Jaunisse sévère, fatigue intense, douleurs abdominales, nausées, cirrhose accélérée', 'cause' => 'Virus de l\'hépatite D (VHD) transmis par le sang et rapports sexuels non protégés', 'prevention' => 'Vaccination contre l\'hépatite B, rapports sexuels protégés, matériel médical stérile', 'traitement_naturel' => 'Chardon-Marie pour le foie, curcuma, artichaut, dandelion, éviter l\'alcool', 'gravite' => 'grave', 'contagieux' => 'oui'],
            ['nom' => 'Infections à E. coli', 'categorie' => 'Bactériologie', 'description' => 'Infection par Escherichia coli pouvant causer gastroentérite ou syndrome hémolytique urémique.', 'symptomes' => 'Diarrhée sanglante, crampes abdominales sévères, vomissements, fièvre, insuffisance rénale', 'cause' => 'Consommation de viande mal cuite, eau contaminée, légumes non lavés, contact fécal-oral', 'prevention' => 'Cuisson complète des viandes, lavage des mains, eau potable, hygiène alimentaire stricte', 'traitement_naturel' => 'Ail antibactérien, probiotiques, thym, origan, hydratation intense, charbon actif', 'gravite' => 'grave', 'contagieux' => 'oui'],
            ['nom' => 'Méningite à méningocoque', 'categorie' => 'Bactériologie', 'description' => 'Infection bactérienne fulminante des méninges pouvant tuer en quelques heures.', 'symptomes' => 'Fièvre brutale, raideur de nuque, purpura fulminans, photophobie, vomissements, coma', 'cause' => 'Neisseria meningitidis transmis par gouttelettes respiratoires dans les collectivités', 'prevention' => 'Vaccination méningococcique, éviter contacts proches avec personnes infectées', 'traitement_naturel' => 'Urgence vitale antibiotique — en prévention : propolis, échinacée, zinc, vitamines C et D', 'gravite' => 'grave', 'contagieux' => 'oui'],
            ['nom' => 'Staphylococcie', 'categorie' => 'Bactériologie', 'description' => 'Infection par Staphylococcus aureus pouvant causer abcès, septicémie ou choc toxique.', 'symptomes' => 'Abcès cutanés, fièvre, douleurs, septicémie, pneumonie, endocardite selon la localisation', 'cause' => 'Staphylococcus aureus présent sur la peau, plaies infectées, contact direct, matériel médical', 'prevention' => 'Hygiène des mains, désinfection des plaies, éviter le partage d\'objets personnels', 'traitement_naturel' => 'Miel de Manuka antibactérien, huile d\'arbre à thé, ail, curcuma, propolis', 'gravite' => 'grave', 'contagieux' => 'oui'],

            // MALADIES AFRICAINES SUPPLÉMENTAIRES
            ['nom' => 'Fièvre de la vallée du Rift', 'categorie' => 'Maladies tropicales', 'description' => 'Zoonose virale africaine affectant bétail et humains transmise par moustiques et contact animal.', 'symptomes' => 'Fièvre, maux de tête, douleurs musculaires, hémorragies, atteinte hépatique, encéphalite', 'cause' => 'Virus Phlebovirus transmis par moustiques Aedes ou contact avec animaux infectés au sacrifice', 'prevention' => 'Vaccination du bétail, protection contre moustiques, équipements lors du sacrifice animal', 'traitement_naturel' => 'Plantes immunostimulantes, curcuma, gingembre, vitamine C, repos et hydratation', 'gravite' => 'grave', 'contagieux' => 'oui'],
            ['nom' => 'Schistosomiase urogénitale', 'categorie' => 'Maladies tropicales', 'description' => 'Parasitose due à Schistosoma haematobium causant des lésions de la vessie et des voies génitales.', 'symptomes' => 'Sang dans les urines, douleurs pelviennes, infertilité, cancer de la vessie à long terme', 'cause' => 'Larves de Schistosoma haematobium pénétrant la peau lors de contact avec eau douce contaminée', 'prevention' => 'Éviter baignade en eau douce stagnante en zone endémique, eau potable traitée', 'traitement_naturel' => 'Graines de courge antiparasitaires, artémisia, ail, noix de coco, hygiène stricte', 'gravite' => 'grave', 'contagieux' => 'non'],
            ['nom' => 'Peste bubonique', 'categorie' => 'Maladies tropicales', 'description' => 'Maladie bactérienne causée par Yersinia pestis transmise par les puces des rongeurs.', 'symptomes' => 'Ganglions enflés douloureux (bubons), fièvre élevée, frissons, céphalées, prostration', 'cause' => 'Yersinia pestis transmis par piqûre de puce du rat, contact avec animaux infectés', 'prevention' => 'Contrôle des rongeurs, éviter contact avec animaux morts, insecticides contre les puces', 'traitement_naturel' => 'Urgence antibiotique — en soutien : ail, propolis, échinacée, vitamine C massive', 'gravite' => 'grave', 'contagieux' => 'oui'],
            ['nom' => 'Anthrax (Charbon)', 'categorie' => 'Maladies tropicales', 'description' => 'Infection bactérienne grave due à Bacillus anthracis touchant humains et animaux en Afrique.', 'symptomes' => 'Pustule charbonneuse, œdème, fièvre, essoufflement selon forme cutanée pulmonaire ou digestive', 'cause' => 'Bacillus anthracis via contact avec animaux infectés, spores dans le sol, produits animaux', 'prevention' => 'Vaccination du bétail, équipements de protection, éviter animaux morts suspects', 'traitement_naturel' => 'Urgence antibiotique — en prévention : renforcement immunitaire, zinc, vitamine C', 'gravite' => 'grave', 'contagieux' => 'non'],

            // MALADIES OSTÉO-ARTICULAIRES
            ['nom' => 'Hernie discale', 'categorie' => 'Orthopédie', 'description' => 'Saillie du nucleus pulposus d\'un disque intervertébral comprimant les racines nerveuses.', 'symptomes' => 'Douleur lombaire irradiant dans la jambe, sciatique, engourdissements, faiblesse musculaire', 'cause' => 'Dégénérescence discale liée à l\'âge, efforts de soulèvement, sédentarité, obésité, tabac', 'prevention' => 'Renforcement musculaire dorsal, posture correcte, éviter soulèvements brusques, poids santé', 'traitement_naturel' => 'Harpagophytum, curcuma, arnica, kinésithérapie, yoga, natation, acupuncture', 'gravite' => 'modérée', 'contagieux' => 'non'],
            ['nom' => 'Ostéoarthrose', 'categorie' => 'Orthopédie', 'description' => 'Dégradation progressive du cartilage articulaire causant douleurs et raideurs chroniques.', 'symptomes' => 'Douleurs articulaires mécaniques, raideur matinale courte, craquements, déformation articulaire', 'cause' => 'Vieillissement, surpoids, traumatismes articulaires répétés, facteurs génétiques, sports intensifs', 'prevention' => 'Maintien du poids santé, activité physique adaptée, protection articulaire, alimentation anti-inflammatoire', 'traitement_naturel' => 'Harpagophytum, boswellia, curcuma, collagène, glucosamine, huile de poisson, bains chauds', 'gravite' => 'modérée', 'contagieux' => 'non'],
            ['nom' => 'Fracture de fatigue', 'categorie' => 'Orthopédie', 'description' => 'Fracture osseuse causée par des microtraumatismes répétés sans choc violent unique.', 'symptomes' => 'Douleur localisée progressive à l\'effort, gonflement, sensibilité à la palpation', 'cause' => 'Surmenage sportif, ostéoporose, nutrition déficiente en calcium et vitamine D', 'prevention' => 'Progression graduelle de l\'entraînement, apport suffisant en calcium et vitamine D, repos', 'traitement_naturel' => 'Silice organique, calcium naturel, vitamine D3, plantes reminéralisantes, prêle', 'gravite' => 'modérée', 'contagieux' => 'non'],

            // MALADIES DE LA PEAU SUPPLÉMENTAIRES
            ['nom' => 'Pemphigoïde bulleuse', 'categorie' => 'Dermatologie', 'description' => 'Maladie auto-immune bulleuse touchant surtout les personnes âgées causant des bulles cutanées.', 'symptomes' => 'Grosses bulles tendues sur peau rouge, démangeaisons intenses, érosions, atteinte des muqueuses', 'cause' => 'Réaction auto-immune contre les protéines de jonction épidermique, médicaments déclenchants', 'prevention' => 'Surveillance dermatologique, éviter médicaments déclenchants chez sujets prédisposés', 'traitement_naturel' => 'Aloe vera apaisant, curcuma anti-inflammatoire, huile de nigelle, propolis, oméga-3', 'gravite' => 'grave', 'contagieux' => 'non'],
            ['nom' => 'Ichtyose', 'categorie' => 'Dermatologie', 'description' => 'Maladie génétique de la peau causant une desquamation excessive et une peau très sèche.', 'symptomes' => 'Peau très sèche squameuse, démangeaisons, fissures douloureuses, surinfections cutanées', 'cause' => 'Mutations génétiques affectant la différenciation et desquamation de l\'épiderme', 'prevention' => 'Hydratation intensive permanente, éviter savons agressifs, vêtements doux, chaleur humide', 'traitement_naturel' => 'Huile de coco, beurre de karité, huile d\'avocat, bains à l\'avoine, aloe vera, urée naturelle', 'gravite' => 'modérée', 'contagieux' => 'non'],

            // MALADIES ENDOCRINIENNES SUPPLÉMENTAIRES
            ['nom' => 'Goitre multinodulaire', 'categorie' => 'Endocrinologie', 'description' => 'Augmentation diffuse du volume de la thyroïde avec formation de nodules multiples.', 'symptomes' => 'Gonflement du cou visible, gêne à la déglutition, dysphonie, compression trachéale', 'cause' => 'Carence en iode, facteurs génétiques, tabagisme, certains médicaments goitrigènes', 'prevention' => 'Apport suffisant en iode via alimentation, sel iodé, éviter aliments goitrigènes en excès', 'traitement_naturel' => 'Algues marines riches en iode, noix du Brésil, sélénium, zinc, huile de noix de coco', 'gravite' => 'modérée', 'contagieux' => 'non'],
            ['nom' => 'Insulinome', 'categorie' => 'Endocrinologie', 'description' => 'Tumeur bénigne du pancréas sécrétant de l\'insuline causant des hypoglycémies sévères.', 'symptomes' => 'Hypoglycémies répétées, tremblements, sueurs, confusion, perte de conscience, convulsions', 'cause' => 'Tumeur des cellules bêta du pancréas, dans 10% des cas associée à des syndromes génétiques', 'prevention' => 'Pas de prévention connue, dépistage précoce en cas d\'hypoglycémies inexpliquées récurrentes', 'traitement_naturel' => 'Cannelle régulatrice, chrome, repas fréquents, éviter sucres rapides, graines de fenugrec', 'gravite' => 'grave', 'contagieux' => 'non'],

            // MALADIES RÉNALES SUPPLÉMENTAIRES
            ['nom' => 'Glomérulonéphrite', 'categorie' => 'Urologie', 'description' => 'Inflammation des glomérules rénaux pouvant mener à l\'insuffisance rénale chronique.', 'symptomes' => 'Urines rougeâtres, œdèmes, hypertension, protéinurie, fatigue, essoufflement', 'cause' => 'Infections streptococciques, maladies auto-immunes, diabète, certains médicaments, génétique', 'prevention' => 'Traitement rapide des infections streptococciques, contrôle du diabète et de la tension', 'traitement_naturel' => 'Ortie diurétique, pissenlit, queue de cerise, réduction sel et protéines, hydratation', 'gravite' => 'grave', 'contagieux' => 'non'],
            ['nom' => 'Polykystose rénale', 'categorie' => 'Urologie', 'description' => 'Maladie génétique causant la formation de nombreux kystes dans les reins conduisant à l\'insuffisance rénale.', 'symptomes' => 'Douleurs lombaires, hypertension, infections urinaires, sang dans les urines, insuffisance rénale', 'cause' => 'Mutations génétiques des gènes PKD1 ou PKD2 transmises de façon autosomique dominante', 'prevention' => 'Pas de prévention possible, contrôle strict de la tension artérielle, hydratation abondante', 'traitement_naturel' => 'Régime pauvre en sel et protéines, curcuma anti-inflammatoire, ortie, hydratation intense', 'gravite' => 'grave', 'contagieux' => 'non'],

            // MALADIES PSYCHIATRIQUES SUPPLÉMENTAIRES
            ['nom' => 'Psychose puerpérale', 'categorie' => 'Psychiatrie', 'description' => 'Trouble psychiatrique grave survenant dans les jours suivant l\'accouchement.', 'symptomes' => 'Confusion, délires, hallucinations, agitation, insomnie sévère, comportement bizarre', 'cause' => 'Bouleversements hormonaux post-partum, prédisposition génétique, antécédents psychiatriques', 'prevention' => 'Suivi psychiatrique pendant grossesse, soutien familial, dépistage précoce des signes', 'traitement_naturel' => 'Oméga-3, millepertuis en complément, soutien psychologique, yoga postnatal, sommeil suffisant', 'gravite' => 'grave', 'contagieux' => 'non'],
            ['nom' => 'Syndrome de Diogène', 'categorie' => 'Psychiatrie', 'description' => 'Trouble du comportement causant une accumulation compulsive d\'objets et une négligence de soi.', 'symptomes' => 'Accumulation excessive d\'objets, négligence hygiénique, isolement social, refus d\'aide', 'cause' => 'Démence, traumatismes psychologiques, dépression sévère, schizophrénie, isolement social', 'prevention' => 'Lien social maintenu, suivi psychiatrique, soutien familial, dépistage des troubles cognitifs', 'traitement_naturel' => 'Thérapie comportementale, plantes adaptogènes, millepertuis, soutien communautaire', 'gravite' => 'modérée', 'contagieux' => 'non'],

            // MALADIES NUTRITIONNELLES
            ['nom' => 'Rachitisme', 'categorie' => 'Nutrition', 'description' => 'Maladie osseuse de l\'enfant due à une carence en vitamine D causant des déformations squelettiques.', 'symptomes' => 'Déformations osseuses, jambes arquées, retard de la fontanelle, faiblesse musculaire, douleurs', 'cause' => 'Carence en vitamine D par manque d\'exposition solaire et alimentation insuffisante', 'prevention' => 'Exposition au soleil quotidienne, supplémentation en vitamine D, lait maternel enrichi', 'traitement_naturel' => 'Exposition solaire progressive, huile de foie de morue, lait de vache, poissons gras, œufs', 'gravite' => 'modérée', 'contagieux' => 'non'],
            ['nom' => 'Scorbut', 'categorie' => 'Nutrition', 'description' => 'Maladie causée par une carence sévère en vitamine C causant des hémorragies et troubles osseux.', 'symptomes' => 'Gencives saignantes, hématomes spontanés, fatigue, douleurs articulaires, cicatrisation lente', 'cause' => 'Carence sévère en vitamine C par alimentation pauvre en fruits et légumes frais', 'prevention' => 'Consommation quotidienne de fruits et légumes frais riches en vitamine C', 'traitement_naturel' => 'Citron, orange, goyave, poivron, persil, kiwi, acérola, rosa canina, supplémentation vitamine C', 'gravite' => 'modérée', 'contagieux' => 'non'],
            ['nom' => 'Kwashiorkor', 'categorie' => 'Nutrition', 'description' => 'Malnutrition protéique sévère de l\'enfant causant œdèmes et retard de croissance en Afrique.', 'symptomes' => 'Œdèmes des jambes et abdomen, cheveux décolorés et fragiles, peau craquelée, apathie', 'cause' => 'Alimentation déficiente en protéines de qualité, sevrage brutal, famine, infections répétées', 'prevention' => 'Alimentation diversifiée riche en protéines, allaitement prolongé, éducation nutritionnelle', 'traitement_naturel' => 'Spiruline, légumineuses, œufs, lait de vache, poissons, moringa riche en protéines', 'gravite' => 'grave', 'contagieux' => 'non'],
            ['nom' => 'Marasme', 'categorie' => 'Nutrition', 'description' => 'Malnutrition énergétique sévère causant une émaciation extrême chez l\'enfant.', 'symptomes' => 'Émaciation sévère, peau flasque, yeux enfoncés, fontanelle déprimée, apathie, irritabilité', 'cause' => 'Apport calorique insuffisant, famine, maladies infectieuses répétées, pauvreté extrême', 'prevention' => 'Accès à une alimentation suffisante, allaitement maternel, prévention des infections', 'traitement_naturel' => 'Réalimentation progressive, lait thérapeutique, moringa, spiruline, bouillie enrichie locale', 'gravite' => 'grave', 'contagieux' => 'non'],
            ['nom' => 'Carence en fer', 'categorie' => 'Nutrition', 'description' => 'Déficit en fer très fréquent en Afrique causant anémie et troubles du développement.', 'symptomes' => 'Fatigue, pâleur, essoufflement, pica, ongles cassants, chute de cheveux, troubles cognitifs', 'cause' => 'Alimentation pauvre en fer, parasitoses intestinales, menstruations abondantes, grossesse', 'prevention' => 'Consommation de viandes rouges, légumineuses, épinards, association avec vitamine C', 'traitement_naturel' => 'Feuilles de moringa, épinards, foie de bœuf, lentilles, abricots secs, ortie, spiruline', 'gravite' => 'modérée', 'contagieux' => 'non'],
            ['nom' => 'Carence en vitamine A', 'categorie' => 'Nutrition', 'description' => 'Déficit en vitamine A causant cécité nocturne et affaiblissement immunitaire chez l\'enfant.', 'symptomes' => 'Cécité nocturne, sécheresse oculaire, xérophtalmie, infections fréquentes, retard de croissance', 'cause' => 'Alimentation pauvre en vitamine A ou bêta-carotène, malabsorption, parasitoses intestinales', 'prevention' => 'Consommation de carottes, mangues, patates douces, huile de palme rouge, légumes verts', 'traitement_naturel' => 'Huile de palme rouge, carotte, papaye, mangue, épinards, foie d\'animal, patate douce orange', 'gravite' => 'grave', 'contagieux' => 'non'],
            ['nom' => 'Pellagre', 'categorie' => 'Nutrition', 'description' => 'Carence en vitamine B3 (niacine) causant dermatite, diarrhée et démence.', 'symptomes' => 'Dermatite symétrique aux zones exposées, diarrhée, démence, inflammation buccale, fatigue', 'cause' => 'Alimentation à base de maïs non nixtamalisé pauvre en niacine, alcoolisme, malabsorption', 'prevention' => 'Diversification alimentaire, légumineuses, viandes, poissons, arachides, levure de bière', 'traitement_naturel' => 'Arachides, poissons, champignons, levure de bière, spiruline, supplémentation en vitamine B3', 'gravite' => 'modérée', 'contagieux' => 'non'],

            // MALADIES DE L\'ENFANT
            ['nom' => 'Paludisme cérébral', 'categorie' => 'Pédiatrie', 'description' => 'Forme grave du paludisme à Plasmodium falciparum causant une encéphalopathie mortelle chez l\'enfant.', 'symptomes' => 'Fièvre très élevée, convulsions, coma, anémie sévère, détresse respiratoire, prostration', 'cause' => 'Plasmodium falciparum transmis par moustique Anopheles femelle infectée la nuit', 'prevention' => 'Moustiquaires imprégnées, répulsifs, chimioprophylaxie, élimination des eaux stagnantes', 'traitement_naturel' => 'Artemisia annua (qing hao), feuilles de papaye, neem, citronnelle, quinquina en complément', 'gravite' => 'grave', 'contagieux' => 'non'],
            ['nom' => 'Diarrhée aiguë du nourrisson', 'categorie' => 'Pédiatrie', 'description' => 'Première cause de mortalité infantile en Afrique causée par des infections et malnutrition.', 'symptomes' => 'Selles liquides fréquentes, vomissements, déshydratation, fièvre, irritabilité, fontanelle creuse', 'cause' => 'Rotavirus, E. coli entérotoxinogène, eau contaminée, aliments souillés, manque d\'hygiène', 'prevention' => 'Allaitement maternel, eau potable, hygiène des mains, vaccination rotavirus, SRO disponible', 'traitement_naturel' => 'Solution de réhydratation orale, eau de riz, banane, carottes cuites, zinc, probiotiques', 'gravite' => 'grave', 'contagieux' => 'oui'],
            ['nom' => 'Tétanos néonatal', 'categorie' => 'Pédiatrie', 'description' => 'Tétanos du nouveau-né par contamination du cordon ombilical lors de l\'accouchement.', 'symptomes' => 'Incapacité à téter, trismus, rigidité généralisée, spasmes, opisthotonus, décès fréquent', 'cause' => 'Clostridium tetani contamination du cordon ombilical par instruments non stériles', 'prevention' => 'Vaccination tétanique de la mère, accouchement en milieu stérile, soins cordon propre', 'traitement_naturel' => 'Urgence vitale — en prévention : vaccination, hygiène stricte, soins cordon à l\'alcool', 'gravite' => 'grave', 'contagieux' => 'non'],
        ];

        foreach ($pathologies as $data) {
            Pathologie::create([
                'nom' => $data['nom'],
                'categorie' => $data['categorie'],
                'description' => $data['description'],
                'symptomes' => $data['symptomes'],
                'cause' => $data['cause'],
                'prevention' => $data['prevention'],
                'traitement_naturel' => $data['traitement_naturel'],
                'gravite' => $data['gravite'],
                'contagieux' => $data['contagieux'],
                'approuve' => true,
                'user_id' => $user->id,
            ]);
        }

        $this->command->info('✅ ' . count($pathologies) . ' pathologies avec causes ajoutées !');
    }
}