<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pathologie;
use App\Models\User;

class MassPathologieSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first();

        $pathologies = [
            // CARDIOLOGIE
            ['nom' => 'Infarctus du myocarde', 'categorie' => 'Cardiologie', 'description' => 'Nécrose d\'une partie du muscle cardiaque due à l\'obstruction d\'une artère coronaire.', 'symptomes' => 'Douleur thoracique intense, essoufflement, sueurs froides, nausées'],
            ['nom' => 'Insuffisance cardiaque', 'categorie' => 'Cardiologie', 'description' => 'Incapacité du cœur à pomper suffisamment de sang pour répondre aux besoins de l\'organisme.', 'symptomes' => 'Essoufflement, fatigue, œdèmes des jambes, prise de poids rapide'],
            ['nom' => 'Fibrillation auriculaire', 'categorie' => 'Cardiologie', 'description' => 'Arythmie cardiaque caractérisée par des contractions irrégulières et rapides des oreillettes.', 'symptomes' => 'Palpitations, essoufflement, fatigue, vertiges, douleur thoracique'],
            ['nom' => 'Angine de poitrine', 'categorie' => 'Cardiologie', 'description' => 'Douleur thoracique causée par une insuffisance d\'apport en oxygène au muscle cardiaque.', 'symptomes' => 'Douleur ou pression thoracique, essoufflement, douleur irradiant dans le bras gauche'],
            ['nom' => 'Cardiopathie congénitale', 'categorie' => 'Cardiologie', 'description' => 'Malformation du cœur présente dès la naissance affectant sa structure et son fonctionnement.', 'symptomes' => 'Cyanose, essoufflement, retard de croissance, fatigue excessive'],
            ['nom' => 'Péricardite', 'categorie' => 'Cardiologie', 'description' => 'Inflammation du péricarde, la membrane qui entoure le cœur.', 'symptomes' => 'Douleur thoracique aiguë, fièvre, fatigue, toux sèche'],
            ['nom' => 'Thrombose veineuse profonde', 'categorie' => 'Cardiologie', 'description' => 'Formation d\'un caillot sanguin dans une veine profonde, généralement dans les jambes.', 'symptomes' => 'Douleur et gonflement du mollet, rougeur, chaleur locale, fièvre'],
            ['nom' => 'Embolie pulmonaire', 'categorie' => 'Cardiologie', 'description' => 'Obstruction d\'une artère pulmonaire par un caillot sanguin migrant depuis les veines.', 'symptomes' => 'Essoufflement soudain, douleur thoracique, toux avec sang, tachycardie'],
            ['nom' => 'Endocardite', 'categorie' => 'Cardiologie', 'description' => 'Infection de l\'endocarde, la paroi interne du cœur, souvent due à des bactéries.', 'symptomes' => 'Fièvre, frissons, fatigue, souffle cardiaque, douleurs articulaires'],
            ['nom' => 'Valvulopathie mitrale', 'categorie' => 'Cardiologie', 'description' => 'Anomalie de la valve mitrale du cœur affectant le flux sanguin entre les cavités cardiaques.', 'symptomes' => 'Essoufflement, fatigue, palpitations, toux, œdèmes'],

            // NEUROLOGIE
            ['nom' => 'Accident vasculaire cérébral', 'categorie' => 'Neurologie', 'description' => 'Interruption de l\'apport sanguin au cerveau causant des lésions neurologiques.', 'symptomes' => 'Paralysie faciale, faiblesse d\'un côté, troubles de la parole, maux de tête sévères'],
            ['nom' => 'Épilepsie', 'categorie' => 'Neurologie', 'description' => 'Trouble neurologique chronique caractérisé par des crises récurrentes dues à des décharges électriques anormales.', 'symptomes' => 'Convulsions, perte de conscience, confusion, mouvements incontrôlés'],
            ['nom' => 'Maladie de Parkinson', 'categorie' => 'Neurologie', 'description' => 'Maladie neurodégénérative progressive affectant le contrôle des mouvements.', 'symptomes' => 'Tremblements au repos, rigidité musculaire, lenteur des mouvements, instabilité posturale'],
            ['nom' => 'Sclérose en plaques', 'categorie' => 'Neurologie', 'description' => 'Maladie auto-immune chronique du système nerveux central affectant la myéline.', 'symptomes' => 'Fatigue, troubles visuels, faiblesse musculaire, problèmes d\'équilibre, engourdissements'],
            ['nom' => 'Maladie d\'Alzheimer', 'categorie' => 'Neurologie', 'description' => 'Maladie neurodégénérative progressive causant une détérioration de la mémoire et des fonctions cognitives.', 'symptomes' => 'Perte de mémoire, confusion, désorientation, troubles du langage, changements de personnalité'],
            ['nom' => 'Méningite', 'categorie' => 'Neurologie', 'description' => 'Inflammation des méninges, les membranes entourant le cerveau et la moelle épinière.', 'symptomes' => 'Fièvre élevée, maux de tête sévères, raideur de la nuque, sensibilité à la lumière'],
            ['nom' => 'Névralgie trigéminale', 'categorie' => 'Neurologie', 'description' => 'Douleur faciale intense et soudaine due à une irritation du nerf trijumeau.', 'symptomes' => 'Douleur faciale fulgurante, décharges électriques dans le visage, sensibilité au toucher'],
            ['nom' => 'Narcolepsie', 'categorie' => 'Neurologie', 'description' => 'Trouble du sommeil chronique caractérisé par une somnolence diurne excessive et soudaine.', 'symptomes' => 'Somnolence excessive, cataplexie, paralysie du sommeil, hallucinations hypnagogiques'],
            ['nom' => 'Syndrome de Guillain-Barré', 'categorie' => 'Neurologie', 'description' => 'Maladie auto-immune rare où le système immunitaire attaque le système nerveux périphérique.', 'symptomes' => 'Faiblesse musculaire progressive, paralysie, picotements, douleurs dans les membres'],
            ['nom' => 'Démence vasculaire', 'categorie' => 'Neurologie', 'description' => 'Déclin cognitif causé par des lésions cérébrales dues à des problèmes vasculaires.', 'symptomes' => 'Confusion, troubles de la mémoire, difficultés de concentration, changements d\'humeur'],

            // PNEUMOLOGIE
            ['nom' => 'Bronchite chronique', 'categorie' => 'Pneumologie', 'description' => 'Inflammation chronique des bronches avec production excessive de mucus.', 'symptomes' => 'Toux productive chronique, expectoration, essoufflement, sifflements'],
            ['nom' => 'Pneumonie', 'categorie' => 'Pneumologie', 'description' => 'Infection pulmonaire causant une inflammation des alvéoles remplies de liquide ou de pus.', 'symptomes' => 'Fièvre, toux avec mucus, essoufflement, douleur thoracique, frissons'],
            ['nom' => 'Tuberculose', 'categorie' => 'Pneumologie', 'description' => 'Infection bactérienne contagieuse affectant principalement les poumons causée par Mycobacterium tuberculosis.', 'symptomes' => 'Toux persistante avec sang, fièvre nocturne, sueurs nocturnes, perte de poids, fatigue'],
            ['nom' => 'Emphysème pulmonaire', 'categorie' => 'Pneumologie', 'description' => 'Destruction progressive des alvéoles pulmonaires réduisant la capacité respiratoire.', 'symptomes' => 'Essoufflement progressif, toux chronique, respiration sifflante, fatigue'],
            ['nom' => 'Pleurésie', 'categorie' => 'Pneumologie', 'description' => 'Inflammation de la plèvre, la membrane entourant les poumons, causant des douleurs respiratoires.', 'symptomes' => 'Douleur thoracique aiguë lors de la respiration, toux sèche, essoufflement, fièvre'],
            ['nom' => 'Fibrose pulmonaire', 'categorie' => 'Pneumologie', 'description' => 'Cicatrisation progressive du tissu pulmonaire réduisant la capacité des poumons à fonctionner.', 'symptomes' => 'Essoufflement progressif, toux sèche, fatigue, perte de poids, douleur musculaire'],
            ['nom' => 'Apnée du sommeil', 'categorie' => 'Pneumologie', 'description' => 'Trouble respiratoire du sommeil caractérisé par des pauses répétées de la respiration.', 'symptomes' => 'Ronflements forts, pauses respiratoires, somnolence diurne, maux de tête matinaux'],
            ['nom' => 'Silicose', 'categorie' => 'Pneumologie', 'description' => 'Maladie pulmonaire professionnelle causée par l\'inhalation de poussières de silice cristalline.', 'symptomes' => 'Toux chronique, essoufflement progressif, fatigue, douleur thoracique'],
            ['nom' => 'Sarcoïdose', 'categorie' => 'Pneumologie', 'description' => 'Maladie inflammatoire chronique formant des amas de cellules dans les poumons et autres organes.', 'symptomes' => 'Essoufflement, toux sèche, fatigue, douleurs articulaires, éruptions cutanées'],
            ['nom' => 'Hypertension pulmonaire', 'categorie' => 'Pneumologie', 'description' => 'Pression artérielle élevée dans les artères pulmonaires affectant le cœur droit.', 'symptomes' => 'Essoufflement, fatigue, vertiges, douleur thoracique, œdèmes des jambes'],

            // GASTROENTÉROLOGIE
            ['nom' => 'Maladie de Crohn', 'categorie' => 'Gastroentérologie', 'description' => 'Maladie inflammatoire chronique pouvant affecter n\'importe quelle partie du tube digestif.', 'symptomes' => 'Douleurs abdominales, diarrhée chronique, perte de poids, fatigue, fièvre'],
            ['nom' => 'Rectocolite hémorragique', 'categorie' => 'Gastroentérologie', 'description' => 'Maladie inflammatoire chronique du côlon et du rectum causant des ulcérations.', 'symptomes' => 'Diarrhée sanglante, crampes abdominales, urgences défécatoires, fatigue, fièvre'],
            ['nom' => 'Syndrome du côlon irritable', 'categorie' => 'Gastroentérologie', 'description' => 'Trouble fonctionnel intestinal chronique causant douleurs et troubles du transit.', 'symptomes' => 'Douleurs abdominales, ballonnements, diarrhée ou constipation alternées, mucus dans les selles'],
            ['nom' => 'Hépatite B', 'categorie' => 'Gastroentérologie', 'description' => 'Infection virale du foie transmissible par le sang et les fluides corporels.', 'symptomes' => 'Jaunisse, fatigue, douleurs abdominales, nausées, urine foncée, selles décolorées'],
            ['nom' => 'Hépatite C', 'categorie' => 'Gastroentérologie', 'description' => 'Infection virale chronique du foie transmise principalement par le sang contaminé.', 'symptomes' => 'Fatigue, douleur abdominale, nausées, jaunisse, démangeaisons, arthralgies'],
            ['nom' => 'Cirrhose hépatique', 'categorie' => 'Gastroentérologie', 'description' => 'Cicatrisation avancée du foie causant une perte progressive de ses fonctions vitales.', 'symptomes' => 'Jaunisse, ascite, fatigue, saignements faciles, confusion mentale, perte de poids'],
            ['nom' => 'Pancréatite', 'categorie' => 'Gastroentérologie', 'description' => 'Inflammation du pancréas pouvant être aiguë ou chronique causant de fortes douleurs.', 'symptomes' => 'Douleur abdominale sévère, nausées, vomissements, fièvre, jaunisse'],
            ['nom' => 'Reflux gastro-œsophagien', 'categorie' => 'Gastroentérologie', 'description' => 'Remontée du contenu gastrique acide dans l\'œsophage causant des brûlures.', 'symptomes' => 'Brûlures d\'estomac, régurgitations acides, toux chronique, difficultés à avaler'],
            ['nom' => 'Ulcère gastroduodénal', 'categorie' => 'Gastroentérologie', 'description' => 'Plaie douloureuse sur la muqueuse de l\'estomac ou du duodénum.', 'symptomes' => 'Douleur épigastrique, nausées, vomissements, perte d\'appétit, selles noires'],
            ['nom' => 'Diverticulite', 'categorie' => 'Gastroentérologie', 'description' => 'Inflammation ou infection de petites poches formées dans la paroi du côlon.', 'symptomes' => 'Douleur abdominale gauche, fièvre, nausées, constipation ou diarrhée, ballonnements'],

            // ENDOCRINOLOGIE
            ['nom' => 'Diabète de type 1', 'categorie' => 'Endocrinologie', 'description' => 'Maladie auto-immune chronique détruisant les cellules productrices d\'insuline du pancréas.', 'symptomes' => 'Soif excessive, mictions fréquentes, perte de poids, fatigue, vision floue'],
            ['nom' => 'Hypothyroïdie', 'categorie' => 'Endocrinologie', 'description' => 'Production insuffisante d\'hormones thyroïdiennes ralentissant le métabolisme.', 'symptomes' => 'Fatigue, prise de poids, sensibilité au froid, peau sèche, constipation, dépression'],
            ['nom' => 'Hyperthyroïdie', 'categorie' => 'Endocrinologie', 'description' => 'Production excessive d\'hormones thyroïdiennes accélérant le métabolisme.', 'symptomes' => 'Perte de poids, palpitations, nervosité, transpiration excessive, tremblements, insomnie'],
            ['nom' => 'Syndrome de Cushing', 'categorie' => 'Endocrinologie', 'description' => 'Excès de cortisol dans l\'organisme causant de nombreuses complications métaboliques.', 'symptomes' => 'Prise de poids abdominale, visage lunaire, vergetures pourpres, hypertension, fatigue'],
            ['nom' => 'Maladie d\'Addison', 'categorie' => 'Endocrinologie', 'description' => 'Insuffisance surrénalienne chronique causant un manque de cortisol et d\'aldostérone.', 'symptomes' => 'Fatigue extrême, perte de poids, hypotension, hyperpigmentation, nausées, dépression'],
            ['nom' => 'Acromégalie', 'categorie' => 'Endocrinologie', 'description' => 'Excès d\'hormone de croissance chez l\'adulte causant une croissance anormale des tissus.', 'symptomes' => 'Élargissement des mains et pieds, traits du visage grossiers, douleurs articulaires, céphalées'],
            ['nom' => 'Syndrome des ovaires polykystiques', 'categorie' => 'Endocrinologie', 'description' => 'Trouble hormonal féminin causant des irrégularités menstruelles et une hyperandrogénie.', 'symptomes' => 'Irrégularités menstruelles, acné, hirsutisme, prise de poids, infertilité'],
            ['nom' => 'Diabète insipide', 'categorie' => 'Endocrinologie', 'description' => 'Trouble de la régulation de l\'eau causant une soif excessive et une production d\'urine abondante.', 'symptomes' => 'Soif intense, mictions très fréquentes, urine très diluée, fatigue, déshydratation'],
            ['nom' => 'Phéochromocytome', 'categorie' => 'Endocrinologie', 'description' => 'Tumeur rare des glandes surrénales sécrétant des hormones causant une hypertension.', 'symptomes' => 'Hypertension sévère, céphalées, palpitations, transpiration excessive, anxiété'],
            ['nom' => 'Ostéoporose', 'categorie' => 'Endocrinologie', 'description' => 'Diminution de la densité osseuse augmentant le risque de fractures spontanées.', 'symptomes' => 'Fractures fréquentes, douleurs dorsales, perte de taille, posture courbée'],

            // DERMATOLOGIE
            ['nom' => 'Psoriasis', 'categorie' => 'Dermatologie', 'description' => 'Maladie inflammatoire chronique de la peau causant des plaques rouges et squameuses.', 'symptomes' => 'Plaques rouges squameuses, démangeaisons, peau sèche et craquelée, douleurs articulaires'],
            ['nom' => 'Acné vulgaire', 'categorie' => 'Dermatologie', 'description' => 'Maladie inflammatoire des follicules pilo-sébacés causant des boutons et comédons.', 'symptomes' => 'Boutons, points noirs, points blancs, kystes, rougeurs, cicatrices'],
            ['nom' => 'Urticaire', 'categorie' => 'Dermatologie', 'description' => 'Réaction cutanée allergique causant des plaques rouges et gonflées très prurigineuses.', 'symptomes' => 'Plaques rouges en relief, démangeaisons intenses, gonflement, brûlures cutanées'],
            ['nom' => 'Vitiligo', 'categorie' => 'Dermatologie', 'description' => 'Maladie auto-immune causant la destruction des mélanocytes et des taches blanches sur la peau.', 'symptomes' => 'Taches blanches sur la peau, dépigmentation progressive, sensibilité au soleil'],
            ['nom' => 'Rosacée', 'categorie' => 'Dermatologie', 'description' => 'Maladie inflammatoire chronique de la peau du visage causant des rougeurs persistantes.', 'symptomes' => 'Rougeurs faciales, vaisseaux sanguins visibles, boutons, yeux irrités, peau épaissie'],
            ['nom' => 'Dermatite de contact', 'categorie' => 'Dermatologie', 'description' => 'Réaction inflammatoire de la peau suite au contact avec une substance irritante ou allergène.', 'symptomes' => 'Rougeurs, démangeaisons, vésicules, gonflement, peau sèche et craquelée'],
            ['nom' => 'Mycose cutanée', 'categorie' => 'Dermatologie', 'description' => 'Infection fongique de la peau causée par des champignons microscopiques pathogènes.', 'symptomes' => 'Démangeaisons, rougeurs, desquamation, taches blanches ou brunes, odeur désagréable'],
            ['nom' => 'Herpès cutané', 'categorie' => 'Dermatologie', 'description' => 'Infection virale chronique causant des lésions vésiculaires douloureuses récurrentes.', 'symptomes' => 'Vésicules douloureuses, brûlures, démangeaisons, croûtes, ganglions enflés'],
            ['nom' => 'Zona', 'categorie' => 'Dermatologie', 'description' => 'Réactivation du virus varicelle-zona causant une éruption douloureuse unilatérale.', 'symptomes' => 'Douleur intense, éruption vésiculaire unilatérale, brûlures, sensibilité cutanée, fièvre'],
            ['nom' => 'Mélanome', 'categorie' => 'Dermatologie', 'description' => 'Cancer de la peau développé à partir des mélanocytes pouvant être très agressif.', 'symptomes' => 'Grain de beauté changeant d\'aspect, asymétrie, bords irréguliers, couleurs multiples, diamètre croissant'],

            // RHUMATOLOGIE
            ['nom' => 'Polyarthrite rhumatoïde', 'categorie' => 'Rhumatologie', 'description' => 'Maladie auto-immune chronique causant une inflammation des articulations et des dommages articulaires.', 'symptomes' => 'Douleurs articulaires symétriques, raideur matinale, gonflement, fatigue, fièvre légère'],
            ['nom' => 'Lupus érythémateux', 'categorie' => 'Rhumatologie', 'description' => 'Maladie auto-immune systémique pouvant affecter de nombreux organes dont les articulations.', 'symptomes' => 'Éruption en papillon, douleurs articulaires, fatigue, sensibilité au soleil, fièvre'],
            ['nom' => 'Goutte', 'categorie' => 'Rhumatologie', 'description' => 'Arthrite inflammatoire causée par le dépôt de cristaux d\'acide urique dans les articulations.', 'symptomes' => 'Douleur articulaire intense soudaine, gonflement, rougeur, chaleur, fièvre'],
            ['nom' => 'Spondylarthrite ankylosante', 'categorie' => 'Rhumatologie', 'description' => 'Maladie inflammatoire chronique affectant principalement la colonne vertébrale et le bassin.', 'symptomes' => 'Douleur et raideur lombaire, raideur matinale, douleur sacro-iliaque, fatigue'],
            ['nom' => 'Fibromyalgie', 'categorie' => 'Rhumatologie', 'description' => 'Syndrome chronique causant des douleurs musculosquelettiques diffuses et une fatigue intense.', 'symptomes' => 'Douleurs musculaires diffuses, fatigue chronique, troubles du sommeil, troubles cognitifs'],
            ['nom' => 'Sclérodermie', 'categorie' => 'Rhumatologie', 'description' => 'Maladie auto-immune causant un durcissement et un épaississement de la peau et des tissus.', 'symptomes' => 'Durcissement de la peau, phénomène de Raynaud, difficultés à avaler, essoufflement'],
            ['nom' => 'Syndrome de Sjögren', 'categorie' => 'Rhumatologie', 'description' => 'Maladie auto-immune chronique affectant les glandes productrices de sécrétions.', 'symptomes' => 'Sécheresse oculaire, sécheresse buccale, fatigue, douleurs articulaires, difficultés à avaler'],
            ['nom' => 'Tendinite', 'categorie' => 'Rhumatologie', 'description' => 'Inflammation d\'un tendon causant douleur et sensibilité au mouvement.', 'symptomes' => 'Douleur locale, sensibilité au toucher, gonflement, raideur, douleur au mouvement'],
            ['nom' => 'Bursite', 'categorie' => 'Rhumatologie', 'description' => 'Inflammation des bourses séreuses protégeant les articulations causant douleur et gonflement.', 'symptomes' => 'Douleur articulaire, gonflement, sensibilité au toucher, rougeur, limitation des mouvements'],
            ['nom' => 'Syndrome du canal carpien', 'categorie' => 'Rhumatologie', 'description' => 'Compression du nerf médian dans le canal carpien causant douleur et engourdissement.', 'symptomes' => 'Engourdissement, picotements dans les doigts, douleur nocturne, faiblesse de la main'],

            // OPHTALMOLOGIE
            ['nom' => 'Glaucome', 'categorie' => 'Ophtalmologie', 'description' => 'Maladie oculaire caractérisée par une pression intraoculaire élevée endommageant le nerf optique.', 'symptomes' => 'Perte progressive de la vision périphérique, halos lumineux, douleur oculaire, vision floue'],
            ['nom' => 'Cataracte', 'categorie' => 'Ophtalmologie', 'description' => 'Opacification progressive du cristallin de l\'œil causant une diminution de la vision.', 'symptomes' => 'Vision floue, sensibilité à la lumière, vision double, couleurs ternes, vision nocturne réduite'],
            ['nom' => 'Dégénérescence maculaire', 'categorie' => 'Ophtalmologie', 'description' => 'Détérioration de la macula causant une perte progressive de la vision centrale.', 'symptomes' => 'Vision centrale floue, lignes droites déformées, difficulté à lire, tache sombre centrale'],
            ['nom' => 'Conjonctivite', 'categorie' => 'Ophtalmologie', 'description' => 'Inflammation de la conjonctive oculaire d\'origine virale, bactérienne ou allergique.', 'symptomes' => 'Yeux rouges, démangeaisons, larmoiement, sécrétions, sensation de corps étranger'],
            ['nom' => 'Rétinopathie diabétique', 'categorie' => 'Ophtalmologie', 'description' => 'Complication du diabète affectant les vaisseaux sanguins de la rétine.', 'symptomes' => 'Vision floue, taches dans la vision, difficultés à voir la nuit, perte de vision'],
            ['nom' => 'Strabisme', 'categorie' => 'Ophtalmologie', 'description' => 'Défaut d\'alignement des yeux causant une vision double ou une amblyopie chez l\'enfant.', 'symptomes' => 'Yeux mal alignés, vision double, clignement fréquent, penchement de la tête'],
            ['nom' => 'Kératocône', 'categorie' => 'Ophtalmologie', 'description' => 'Amincissement progressif de la cornée qui prend une forme conique déformant la vision.', 'symptomes' => 'Vision floue et distordue, sensibilité à la lumière, halos, besoin fréquent de changer de lunettes'],
            ['nom' => 'Uvéite', 'categorie' => 'Ophtalmologie', 'description' => 'Inflammation de l\'uvée, la couche intermédiaire de l\'œil pouvant causer des complications graves.', 'symptomes' => 'Douleur oculaire, rougeur, vision floue, sensibilité à la lumière, flotteurs visuels'],
            ['nom' => 'Décollement de rétine', 'categorie' => 'Ophtalmologie', 'description' => 'Séparation de la rétine de la couche sous-jacente constituant une urgence ophtalmologique.', 'symptomes' => 'Flashes lumineux, corps flottants, voile sombre dans la vision, perte soudaine de vision'],
            ['nom' => 'Amblyopie', 'categorie' => 'Ophtalmologie', 'description' => 'Réduction de l\'acuité visuelle d\'un œil sans cause organique détectable appelée œil paresseux.', 'symptomes' => 'Mauvaise vision d\'un œil, difficultés de profondeur, plissement des yeux, strabisme'],

            // ORL
            ['nom' => 'Sinusite chronique', 'categorie' => 'ORL', 'description' => 'Inflammation persistante des sinus paranasaux durant plus de 12 semaines.', 'symptomes' => 'Congestion nasale, douleur faciale, perte d\'odorat, écoulement nasal, maux de tête'],
            ['nom' => 'Otite moyenne', 'categorie' => 'ORL', 'description' => 'Infection de l\'oreille moyenne fréquente chez l\'enfant causant douleur et fièvre.', 'symptomes' => 'Douleur d\'oreille, fièvre, perte auditive temporaire, irritabilité, écoulement d\'oreille'],
            ['nom' => 'Acouphènes', 'categorie' => 'ORL', 'description' => 'Perception de sons sans source sonore externe pouvant être chroniques et invalidants.', 'symptomes' => 'Bourdonnements, sifflements, tintements dans les oreilles, troubles du sommeil, anxiété'],
            ['nom' => 'Vertiges de Ménière', 'categorie' => 'ORL', 'description' => 'Maladie de l\'oreille interne causant des vertiges, acouphènes et perte auditive.', 'symptomes' => 'Vertiges intenses, acouphènes, perte auditive fluctuante, sensation de plénitude auriculaire'],
            ['nom' => 'Laryngite', 'categorie' => 'ORL', 'description' => 'Inflammation du larynx causant une altération de la voix allant jusqu\'à l\'aphonie.', 'symptomes' => 'Enrouement, perte de voix, douleur à la gorge, toux sèche, difficultés à avaler'],
            ['nom' => 'Angine streptococcique', 'categorie' => 'ORL', 'description' => 'Infection bactérienne de la gorge due au streptocoque causant une pharyngite sévère.', 'symptomes' => 'Mal de gorge intense, fièvre élevée, difficultés à avaler, ganglions enflés, amygdales rouges'],
            ['nom' => 'Rhinite allergique', 'categorie' => 'ORL', 'description' => 'Inflammation de la muqueuse nasale due à une allergie aux pollens, acariens ou animaux.', 'symptomes' => 'Éternuements, écoulement nasal, congestion, démangeaisons nasales, yeux larmoyants'],
            ['nom' => 'Surdité de perception', 'categorie' => 'ORL', 'description' => 'Perte auditive due à une atteinte de l\'oreille interne ou du nerf auditif.', 'symptomes' => 'Difficultés à entendre, incompréhension de la parole, besoin d\'augmenter le volume'],
            ['nom' => 'Aphasie', 'categorie' => 'ORL', 'description' => 'Trouble du langage acquis suite à une lésion cérébrale affectant la production et la compréhension.', 'symptomes' => 'Difficultés à parler, manque du mot, incompréhension verbale, lecture et écriture difficiles'],
            ['nom' => 'Polypes nasaux', 'categorie' => 'ORL', 'description' => 'Excroissances bénignes dans les fosses nasales causant obstruction et troubles olfactifs.', 'symptomes' => 'Obstruction nasale, perte d\'odorat, écoulement nasal, maux de tête, ronflement'],

            // UROLOGIE
            ['nom' => 'Insuffisance rénale chronique', 'categorie' => 'Urologie', 'description' => 'Détérioration progressive et irréversible de la fonction rénale sur plusieurs mois ou années.', 'symptomes' => 'Fatigue, œdèmes, hypertension, nausées, diminution de la diurèse, anémie'],
            ['nom' => 'Lithiase urinaire', 'categorie' => 'Urologie', 'description' => 'Formation de calculs dans les voies urinaires causant des douleurs intenses.', 'symptomes' => 'Colique néphrétique, sang dans les urines, douleur lombaire, nausées, vomissements'],
            ['nom' => 'Infection urinaire', 'categorie' => 'Urologie', 'description' => 'Infection bactérienne des voies urinaires très fréquente surtout chez la femme.', 'symptomes' => 'Brûlures mictionnelles, mictions fréquentes, urines troubles, douleur pelvienne, fièvre'],
            ['nom' => 'Prostatite', 'categorie' => 'Urologie', 'description' => 'Inflammation de la prostate pouvant être aiguë ou chronique causant des troubles urinaires.', 'symptomes' => 'Douleur pelvienne, difficultés à uriner, fréquence mictionnelle, fièvre, douleur éjaculatoire'],
            ['nom' => 'Hypertrophie bénigne de la prostate', 'categorie' => 'Urologie', 'description' => 'Augmentation non cancéreuse du volume de la prostate fréquente chez l\'homme âgé.', 'symptomes' => 'Difficultés à uriner, jet faible, mictions fréquentes nocturnes, impression de vidange incomplète'],
            ['nom' => 'Incontinence urinaire', 'categorie' => 'Urologie', 'description' => 'Perte involontaire d\'urine pouvant affecter significativement la qualité de vie.', 'symptomes' => 'Fuites urinaires involontaires, urgences mictionnelles, fuites à l\'effort, énurésie'],
            ['nom' => 'Pyélonéphrite', 'categorie' => 'Urologie', 'description' => 'Infection bactérienne du rein et du bassinet pouvant être grave si non traitée.', 'symptomes' => 'Fièvre élevée, douleur lombaire, frissons, nausées, brûlures urinaires, urines troubles'],
            ['nom' => 'Syndrome néphrotique', 'categorie' => 'Urologie', 'description' => 'Atteinte rénale causant une fuite massive de protéines dans les urines.', 'symptomes' => 'Œdèmes importants, urines mousseuses, prise de poids, fatigue, hypertension'],
            ['nom' => 'Cancer de la vessie', 'categorie' => 'Urologie', 'description' => 'Tumeur maligne développée dans la paroi de la vessie souvent liée au tabac.', 'symptomes' => 'Sang dans les urines, mictions douloureuses, urgences mictionnelles, douleur pelvienne'],
            ['nom' => 'Dysfonction érectile', 'categorie' => 'Urologie', 'description' => 'Incapacité persistante à obtenir ou maintenir une érection suffisante pour une activité sexuelle.', 'symptomes' => 'Érections insuffisantes, diminution de la libido, anxiété, dépression, problèmes relationnels'],

            // GYNÉCOLOGIE
            ['nom' => 'Endométriose', 'categorie' => 'Gynécologie', 'description' => 'Présence de tissu endométrial en dehors de l\'utérus causant douleurs et infertilité.', 'symptomes' => 'Douleurs pelviennes intenses, dysménorrhée, douleurs pendant les rapports, infertilité'],
            ['nom' => 'Fibromes utérins', 'categorie' => 'Gynécologie', 'description' => 'Tumeurs bénignes du muscle utérin très fréquentes chez la femme en âge de procréer.', 'symptomes' => 'Règles abondantes, douleurs pelviennes, fréquence urinaire, constipation, ballonnements'],
            ['nom' => 'Cancer du col de l\'utérus', 'categorie' => 'Gynécologie', 'description' => 'Cancer du col utérin lié dans la majorité des cas au papillomavirus humain HPV.', 'symptomes' => 'Saignements anormaux, pertes vaginales inhabituelles, douleurs pelviennes, douleur pendant les rapports'],
            ['nom' => 'Ménopause précoce', 'categorie' => 'Gynécologie', 'description' => 'Arrêt des règles avant 40 ans causant une carence en estrogènes avec de nombreuses conséquences.', 'symptomes' => 'Bouffées de chaleur, irrégularités menstruelles, sécheresse vaginale, troubles du sommeil, sautes d\'humeur'],
            ['nom' => 'Vaginite', 'categorie' => 'Gynécologie', 'description' => 'Inflammation du vagin causée par une infection bactérienne, fongique ou virale.', 'symptomes' => 'Pertes vaginales anormales, démangeaisons, brûlures, odeur désagréable, douleurs'],
            ['nom' => 'Salpingite', 'categorie' => 'Gynécologie', 'description' => 'Infection et inflammation des trompes de Fallope pouvant causer l\'infertilité.', 'symptomes' => 'Douleurs pelviennes, fièvre, pertes vaginales anormales, douleurs pendant les rapports'],
            ['nom' => 'Dysménorrhée', 'categorie' => 'Gynécologie', 'description' => 'Règles douloureuses intenses pouvant perturber significativement les activités quotidiennes.', 'symptomes' => 'Crampes abdominales intenses, douleur lombaire, nausées, vomissements, diarrhée, céphalées'],
            ['nom' => 'Syndrome prémenstruel', 'categorie' => 'Gynécologie', 'description' => 'Ensemble de symptômes physiques et émotionnels survenant avant les règles.', 'symptomes' => 'Ballonnements, sensibilité des seins, sautes d\'humeur, irritabilité, fatigue, maux de tête'],
            ['nom' => 'Cancer de l\'ovaire', 'categorie' => 'Gynécologie', 'description' => 'Tumeur maligne développée dans un ou les deux ovaires souvent diagnostiquée tardivement.', 'symptomes' => 'Ballonnements persistants, douleurs abdominales, troubles digestifs, fatigue, mictions fréquentes'],
            ['nom' => 'Prolapsus génital', 'categorie' => 'Gynécologie', 'description' => 'Descente d\'un ou plusieurs organes pelviens dans le vagin due à un affaiblissement du plancher pelvien.', 'symptomes' => 'Sensation de pesanteur pelvienne, masse vaginale, incontinence urinaire, difficultés sexuelles'],

            // PÉDIATRIE
            ['nom' => 'Bronchiolite', 'categorie' => 'Pédiatrie', 'description' => 'Infection virale des petites bronches très fréquente chez le nourrisson causant une détresse respiratoire.', 'symptomes' => 'Toux, sifflements respiratoires, difficultés respiratoires, fièvre, refus de boire'],
            ['nom' => 'Varicelle', 'categorie' => 'Pédiatrie', 'description' => 'Maladie virale très contagieuse causant une éruption vésiculaire prurigineuse typique de l\'enfance.', 'symptomes' => 'Éruption vésiculaire, démangeaisons intenses, fièvre, fatigue, perte d\'appétit'],
            ['nom' => 'Rougeole', 'categorie' => 'Pédiatrie', 'description' => 'Maladie virale hautement contagieuse causant fièvre élevée et éruption cutanée caractéristique.', 'symptomes' => 'Fièvre élevée, toux, écoulement nasal, yeux rouges, éruption rouge, taches de Koplik'],
            ['nom' => 'Coqueluche', 'categorie' => 'Pédiatrie', 'description' => 'Infection bactérienne respiratoire causant une toux spasmodique sévère pouvant durer des semaines.', 'symptomes' => 'Toux spasmodique en quintes, reprise inspiratoire sifflante, vomissements après toux, cyanose'],
            ['nom' => 'Scarlatine', 'categorie' => 'Pédiatrie', 'description' => 'Infection bactérienne streptococcique causant fièvre, angine et éruption cutanée caractéristique.', 'symptomes' => 'Fièvre, mal de gorge, éruption rouge granuleuse, langue framboisée, desquamation'],
            ['nom' => 'Otite séreuse', 'categorie' => 'Pédiatrie', 'description' => 'Accumulation de liquide dans l\'oreille moyenne sans signes d\'infection aiguë chez l\'enfant.', 'symptomes' => 'Perte auditive légère, sensation d\'oreille bouchée, retard de langage, inattention'],
            ['nom' => 'Reflux gastro-œsophagien du nourrisson', 'categorie' => 'Pédiatrie', 'description' => 'Remontée du contenu gastrique fréquente chez le nourrisson pouvant causer des complications.', 'symptomes' => 'Régurgitations fréquentes, pleurs après les repas, refus de boire, mauvaise prise de poids'],
            ['nom' => 'Trouble déficitaire de l\'attention', 'categorie' => 'Pédiatrie', 'description' => 'Trouble neurodéveloppemental causant inattention, hyperactivité et impulsivité chez l\'enfant.', 'symptomes' => 'Inattention, hyperactivité, impulsivité, difficultés scolaires, troubles du comportement'],
            ['nom' => 'Autisme', 'categorie' => 'Pédiatrie', 'description' => 'Trouble neurodéveloppemental affectant la communication sociale et le comportement.', 'symptomes' => 'Difficultés de communication, comportements répétitifs, sensibilités sensorielles, isolement social'],
            ['nom' => 'Malnutrition infantile', 'categorie' => 'Pédiatrie', 'description' => 'Déficit nutritionnel grave affectant la croissance et le développement de l\'enfant.', 'symptomes' => 'Retard de croissance, fonte musculaire, œdèmes, cheveux fragiles, immunité affaiblie'],

            // ONCOLOGIE
            ['nom' => 'Cancer du sein', 'categorie' => 'Oncologie', 'description' => 'Tumeur maligne du sein affectant principalement les femmes et nécessitant un dépistage précoce.', 'symptomes' => 'Masse dans le sein, modification de la peau, écoulement du mamelon, ganglions axillaires'],
            ['nom' => 'Cancer du poumon', 'categorie' => 'Oncologie', 'description' => 'Tumeur maligne pulmonaire souvent liée au tabac et l\'une des causes majeures de mortalité par cancer.', 'symptomes' => 'Toux persistante, sang dans les crachats, essoufflement, douleur thoracique, perte de poids'],
            ['nom' => 'Cancer colorectal', 'categorie' => 'Oncologie', 'description' => 'Tumeur maligne du côlon ou du rectum bénéficiant d\'un dépistage par coloscopie.', 'symptomes' => 'Sang dans les selles, changement du transit, douleurs abdominales, fatigue, perte de poids'],
            ['nom' => 'Leucémie', 'categorie' => 'Oncologie', 'description' => 'Cancer des cellules sanguines affectant la moelle osseuse et la production des cellules sanguines.', 'symptomes' => 'Fatigue, pâleur, saignements, infections fréquentes, ganglions enflés, douleurs osseuses'],
            ['nom' => 'Lymphome de Hodgkin', 'categorie' => 'Oncologie', 'description' => 'Cancer du système lymphatique avec un bon pronostic grâce aux traitements modernes.', 'symptomes' => 'Ganglions enflés indolores, fièvre, sueurs nocturnes, perte de poids, démangeaisons'],
            ['nom' => 'Cancer de la prostate', 'categorie' => 'Oncologie', 'description' => 'Tumeur maligne de la prostate fréquente chez l\'homme âgé avec un bon pronostic si détecté tôt.', 'symptomes' => 'Difficultés urinaires, sang dans les urines, douleurs osseuses, dysfonction érectile'],
            ['nom' => 'Cancer de l\'estomac', 'categorie' => 'Oncologie', 'description' => 'Tumeur maligne gastrique souvent diagnostiquée à un stade avancé avec un pronostic réservé.', 'symptomes' => 'Douleurs épigastriques, perte d\'appétit, perte de poids, nausées, sang dans les vomissements'],
            ['nom' => 'Cancer du foie', 'categorie' => 'Oncologie', 'description' => 'Tumeur maligne hépatique souvent liée aux hépatites virales ou à la cirrhose.', 'symptomes' => 'Douleur abdominale droite, jaunisse, ascite, perte de poids, fatigue, fièvre'],
            ['nom' => 'Cancer du pancréas', 'categorie' => 'Oncologie', 'description' => 'Tumeur maligne du pancréas au pronostic très sombre car souvent diagnostiquée tardivement.', 'symptomes' => 'Jaunisse, douleur abdominale irradiant dans le dos, perte de poids, diabète nouveau'],
            ['nom' => 'Myélome multiple', 'categorie' => 'Oncologie', 'description' => 'Cancer des plasmocytes de la moelle osseuse causant des lésions osseuses et une insuffisance rénale.', 'symptomes' => 'Douleurs osseuses, fractures pathologiques, fatigue, infections fréquentes, insuffisance rénale'],

            // PSYCHIATRIE
            ['nom' => 'Trouble bipolaire', 'categorie' => 'Psychiatrie', 'description' => 'Trouble de l\'humeur caractérisé par des épisodes alternant entre dépression et manie.', 'symptomes' => 'Épisodes maniaques, épisodes dépressifs, sautes d\'humeur extrêmes, impulsivité, troubles du sommeil'],
            ['nom' => 'Schizophrénie', 'categorie' => 'Psychiatrie', 'description' => 'Trouble mental sévère affectant la pensée, les émotions et le comportement avec des hallucinations.', 'symptomes' => 'Hallucinations, délires, pensée désorganisée, affect émoussé, isolement social'],
            ['nom' => 'Trouble anxieux généralisé', 'categorie' => 'Psychiatrie', 'description' => 'Anxiété excessive et persistante concernant différents aspects de la vie quotidienne.', 'symptomes' => 'Anxiété excessive, tensions musculaires, troubles du sommeil, fatigue, difficultés de concentration'],
            ['nom' => 'Trouble panique', 'categorie' => 'Psychiatrie', 'description' => 'Survenue répétée de crises de panique soudaines avec peur intense et symptômes physiques.', 'symptomes' => 'Palpitations, transpiration, tremblements, essoufflement, douleur thoracique, peur de mourir'],
            ['nom' => 'Trouble obsessionnel compulsif', 'categorie' => 'Psychiatrie', 'description' => 'Trouble anxieux caractérisé par des pensées obsessionnelles et des comportements compulsifs.', 'symptomes' => 'Obsessions, compulsions, rituels répétitifs, anxiété intense, perte de temps significative'],
            ['nom' => 'Anorexie mentale', 'categorie' => 'Psychiatrie', 'description' => 'Trouble du comportement alimentaire caractérisé par une restriction alimentaire sévère.', 'symptomes' => 'Perte de poids extrême, image corporelle déformée, refus de manger, aménorrhée, fatigue'],
            ['nom' => 'Boulimie', 'categorie' => 'Psychiatrie', 'description' => 'Trouble alimentaire caractérisé par des épisodes de frénésie alimentaire suivis de comportements compensatoires.', 'symptomes' => 'Crises de boulimie, vomissements provoqués, utilisation de laxatifs, sentiment de honte'],
            ['nom' => 'État de stress post-traumatique', 'categorie' => 'Psychiatrie', 'description' => 'Trouble anxieux développé après un événement traumatique intense.', 'symptomes' => 'Flashbacks, cauchemars, hypervigilance, évitement, troubles du sommeil, irritabilité'],
            ['nom' => 'Trouble de la personnalité borderline', 'categorie' => 'Psychiatrie', 'description' => 'Trouble de la personnalité caractérisé par une instabilité émotionnelle et relationnelle intense.', 'symptomes' => 'Instabilité émotionnelle, relations tumultueuses, impulsivité, peur de l\'abandon, automutilation'],
            ['nom' => 'Addiction à l\'alcool', 'categorie' => 'Psychiatrie', 'description' => 'Dépendance chronique à l\'alcool causant de graves conséquences physiques et psychologiques.', 'symptomes' => 'Besoin compulsif de boire, tolérance accrue, sevrage difficile, négligence des responsabilités'],

            // INFECTIOLOGIE
            ['nom' => 'VIH/SIDA', 'categorie' => 'Infectiologie', 'description' => 'Infection virale chronique détruisant le système immunitaire conduisant au SIDA si non traitée.', 'symptomes' => 'Infections opportunistes, perte de poids, fièvre persistante, fatigue, ganglions enflés'],
            ['nom' => 'Paludisme', 'categorie' => 'Infectiologie', 'description' => 'Maladie parasitaire transmise par les moustiques Anophèles sévissant dans les zones tropicales.', 'symptomes' => 'Fièvre cyclique, frissons, sueurs, maux de tête, nausées, douleurs musculaires'],
            ['nom' => 'Typhoïde', 'categorie' => 'Infectiologie', 'description' => 'Infection bactérienne systémique due à Salmonella typhi transmise par l\'eau ou aliments contaminés.', 'symptomes' => 'Fièvre progressive, maux de tête, douleurs abdominales, constipation puis diarrhée, roséole'],
            ['nom' => 'Choléra', 'categorie' => 'Infectiologie', 'description' => 'Infection intestinale aiguë due à Vibrio cholerae causant une diarrhée sévère et déshydratation.', 'symptomes' => 'Diarrhée aqueuse abondante, vomissements, déshydratation sévère, crampes musculaires'],
            ['nom' => 'Dengue', 'categorie' => 'Infectiologie', 'description' => 'Maladie virale transmise par les moustiques Aedes répandue dans les régions tropicales.', 'symptomes' => 'Fièvre élevée, maux de tête intenses, douleurs articulaires et musculaires, éruption cutanée'],
            ['nom' => 'Lèpre', 'categorie' => 'Infectiologie', 'description' => 'Maladie bactérienne chronique affectant la peau, les nerfs et les muqueuses.', 'symptomes' => 'Taches cutanées décolorées, engourdissements, faiblesse musculaire, plaies qui ne guérissent pas'],
            ['nom' => 'Fièvre jaune', 'categorie' => 'Infectiologie', 'description' => 'Maladie virale hémorragique transmise par les moustiques dans les régions tropicales.', 'symptomes' => 'Fièvre, jaunisse, saignements, douleurs musculaires, nausées, vomissements'],
            ['nom' => 'Bilharziose', 'categorie' => 'Infectiologie', 'description' => 'Parasitose due aux vers du genre Schistosoma affectant les organes abdominaux.', 'symptomes' => 'Sang dans les urines, douleurs abdominales, fatigue, anémie, grossissement du foie et rate'],
            ['nom' => 'Trypanosomiase africaine', 'categorie' => 'Infectiologie', 'description' => 'Maladie du sommeil transmise par la mouche tsé-tsé affectant le système nerveux.', 'symptomes' => 'Fièvre, maux de tête, troubles du sommeil, confusion, difficultés à marcher, coma'],
            ['nom' => 'Leishmaniose', 'categorie' => 'Infectiologie', 'description' => 'Maladie parasitaire transmise par les phlébotomes affectant la peau ou les organes internes.', 'symptomes' => 'Ulcères cutanés, fièvre, splénomégalie, hépatite, anémie, perte de poids'],

            // HÉMATOLOGIE
            ['nom' => 'Drépanocytose', 'categorie' => 'Hématologie', 'description' => 'Maladie génétique des globules rouges très répandue en Afrique causant crises douloureuses.', 'symptomes' => 'Crises de douleurs, anémie, infections fréquentes, retard de croissance, jaunisse'],
            ['nom' => 'Thalassémie', 'categorie' => 'Hématologie', 'description' => 'Maladie génétique réduisant la production d\'hémoglobine causant une anémie chronique sévère.', 'symptomes' => 'Anémie sévère, fatigue, pâleur, retard de croissance, déformation osseuse, splénomégalie'],
            ['nom' => 'Hémophilie', 'categorie' => 'Hématologie', 'description' => 'Maladie génétique du système de coagulation causant des saignements prolongés.', 'symptomes' => 'Saignements prolongés, hématomes spontanés, hémarthroses, saignements internes'],
            ['nom' => 'Purpura thrombopénique', 'categorie' => 'Hématologie', 'description' => 'Maladie auto-immune causant une destruction des plaquettes et des saignements cutanés.', 'symptomes' => 'Pétéchies, ecchymoses, saignements des gencives, sang dans les urines, fatigue'],
            ['nom' => 'Polyglobulie de Vaquez', 'categorie' => 'Hématologie', 'description' => 'Syndrome myéloprolifératif causant une surproduction de globules rouges épaississant le sang.', 'symptomes' => 'Rougeur du visage, céphalées, vertiges, prurit aquagénique, thromboses, splénomégalie'],
            ['nom' => 'Leucémie lymphoïde chronique', 'categorie' => 'Hématologie', 'description' => 'Cancer des lymphocytes B à évolution lente touchant principalement les personnes âgées.', 'symptomes' => 'Ganglions enflés, fatigue, infections fréquentes, sueurs nocturnes, perte de poids'],
            ['nom' => 'Aplasie médullaire', 'categorie' => 'Hématologie', 'description' => 'Insuffisance de la moelle osseuse ne produisant plus suffisamment de cellules sanguines.', 'symptomes' => 'Fatigue extrême, infections graves, saignements, pâleur, essoufflement'],
            ['nom' => 'Syndrome des antiphospholipides', 'categorie' => 'Hématologie', 'description' => 'Maladie auto-immune causant une hypercoagulabilité et des thromboses récidivantes.', 'symptomes' => 'Thromboses récidivantes, fausses couches, livedo reticularis, migraine, thrombopénie'],
            ['nom' => 'Mononucléose infectieuse', 'categorie' => 'Hématologie', 'description' => 'Infection virale par le virus Epstein-Barr causant fatigue intense et ganglions.', 'symptomes' => 'Fatigue intense, fièvre, angine sévère, ganglions, splénomégalie, éruption cutanée'],
            ['nom' => 'Hémochromatose', 'categorie' => 'Hématologie', 'description' => 'Maladie génétique causant une surcharge en fer dans l\'organisme endommageant les organes.', 'symptomes' => 'Fatigue, douleurs articulaires, diabète, cirrhose, troubles cardiaques, pigmentation cutanée'],
        ];

        foreach ($pathologies as $data) {
            Pathologie::create([
                'nom' => $data['nom'],
                'categorie' => $data['categorie'],
                'description' => $data['description'],
                'symptomes' => $data['symptomes'],
                'approuve' => true,
                'user_id' => $user->id,
            ]);
        }

        $this->command->info('✅ ' . count($pathologies) . ' pathologies ajoutées avec succès !');
    }
}