services:
  - type: web
    name: biolink
    env: docker
    region: frankfurt
    plan: free
    envVars:
      - key: APP_NAME
        value: BioLink
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:4dNqf5vz7dSDdeU1DnCVHQSDagAHihQqgLDs7J8Gt10=
      - key: APP_URL
        value: https://biolink.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d79liqma2pns73e6kso0-a.frankfurt-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: biolink_db
      - key: DB_USERNAME
        value: biolink_db_user
      - key: DB_PASSWORD
        value: agK21K5M4SxrICwiEm5SyZ8ycDVryjgu
      - key: DATABASE_URL
        value: postgresql://biolink_db_user:agK21K5M4SxrICwiEm5SyZ8ycDVryjgu@dpg-d79liqma2pns73e6kso0-a.frankfurt-postgres.render.com/biolink_db
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync